name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get short comitid
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: raunakvkhatri/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
      -
        name: Argocd spp sync
        shell: bash
        run: |
          argocd login argocd-dex-server.argocd \
              --insecure \
              --grpc-web \
              --username admin \
              --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

      