name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get short comitid
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: raunakvkhatri/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Install yq (Go binary, correct one)
        shell: bash
        run: |
         # Make sure curl is installed
          if ! command -v curl >/dev/null 2>&1; then
            echo "curl not found â€” installing..."
            sudo apt-get update && sudo apt-get install -y curl
          fi
          
          # Download yq safely
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /usr/local/bin/yq
          
          sudo chmod +x /usr/local/bin/yq
          yq --version
      - 
        name: Modify values file
        shell: bash
        run: |
          echo "Updating image tag to: ${{ needs.ci.outputs.commit_id }}"
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml
      - 
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      -
        name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
      -
        name: Argocd spp sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
              --insecure \
              --grpc-web \
              --username admin \
              --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

      